[package]
name = "node_derive"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
regex = "1"
proc-macro2 = "1.0.36"
quote = "1.0.15"
syn = {version = "1.0.86", features = ["full", "extra-traits", "visit-mut", "visit"]}
